"""Generate swiftf0_tables.h (window and projection) from frontend.py.

Copyright 2026 Sher Amir Singh Dullat
SPDX-License-Identifier: Apache-2.0
"""

import numpy as np

from swiftf0 import frontend as fe


def main():
    W = fe.projection_matrix()
    hann = fe.hann_periodic().astype(np.float32)

    starts, counts, weights = [], [], []
    for k in range(fe.NBINS_IN):
        nz = np.nonzero(W[k])[0]
        if nz.size == 0:
            starts.append(0)
            counts.append(0)
            continue
        s, e = int(nz[0]), int(nz[-1])
        assert np.all(W[k, s:e + 1] >= 0) and np.count_nonzero(W[k, :s]) == 0
        starts.append(s)
        counts.append(e - s + 1)
        weights.extend(W[k, s:e + 1].tolist())

    def cf32(v):
        s = f"{v:.9g}"
        if not any(c in s for c in ".eEnN"):
            s += ".0"
        return s + "f"

    def emit_f32(name, arr, per_line=8):
        out = [f"static const float {name}[{len(arr)}] = {{"]
        for i in range(0, len(arr), per_line):
            row = ", ".join(cf32(v) for v in arr[i:i + per_line])
            out.append(f"  {row},")
        out.append("};")
        return "\n".join(out)

    def emit_u16(name, arr, per_line=16):
        out = [f"static const uint16_t {name}[{len(arr)}] = {{"]
        for i in range(0, len(arr), per_line):
            row = ", ".join(str(v) for v in arr[i:i + per_line])
            out.append(f"  {row},")
        out.append("};")
        return "\n".join(out)

    print(f"""/*
 * swiftf0_tables.h - generated by tools/swiftf0/gen_tables.py, do not edit
 *
 * SF0_HANN: periodic Hann window. The projection from FFT magnitudes to the
 * 20-cent grid is stored row by row: row k uses SF0_PROJ_CNT[k] weights from
 * SF0_PROJ_W, applied to FFT bins starting at SF0_PROJ_START[k]. Rows
 * {fe.NBINS_LIVE}..{fe.NBINS_IN - 1} are empty.
 */
#ifndef SWIFTF0_TABLES_H
#define SWIFTF0_TABLES_H
#include <stdint.h>

#define SF0_NFFT      {fe.NFFT}u
#define SF0_NSPEC     {fe.NSPEC}u
#define SF0_NBINS_IN  {fe.NBINS_IN}u
#define SF0_NBINS_LIVE {fe.NBINS_LIVE}u
#define SF0_NBINS_OUT {fe.NBINS_OUT}u
#define SF0_PROJ_NNZ  {len(weights)}u

{emit_f32("SF0_HANN", hann.tolist())}

{emit_u16("SF0_PROJ_START", starts)}

{emit_u16("SF0_PROJ_CNT", counts)}

{emit_f32("SF0_PROJ_W", weights)}

#endif /* SWIFTF0_TABLES_H */""")


if __name__ == "__main__":
    main()
