/* rsn_meta.h - generated by tools/board/gen_rsn_fw.py, do not edit
 * source: deploy/rsn_final_v1 (/scratch/rsn_runs/F2qat/rsn.pt, step 15000, qat=True)
 * arch  : {'ch': 96, 'dilations': [1, 2, 4, 8, 16, 32], 'lookahead': 0}
 */
#pragma once
#include <stdint.h>

/* The NPU RAM image is loaded by tools/board/board.sh from
 * tools/board/blobs/rsn_weights.bin; rsn_npu_init() checks its CRC.
 *   weights: 276960 B
 *   EC blob _ec_blob_rsn_1: 0x242B3A00, 61632 B
 */
#define RSN_WEIGHTS_ADDR   0x24270000UL
#define RSN_WEIGHTS_LEN    338624u      /* whole image: weights + EC blobs */
#define RSN_WEIGHTS_CRC32  0x82FFC619u
#define RSN_EC             1u        /* 1: epoch-controller build (needs LL_ATON_RT_MODE=2) */

#define RSN_WINDOW         352u
#define RSN_HOP            80u
#define RSN_CH_IN          4u
#define RSN_OUT0           272u        /* keep outputs [RSN_OUT0, RSN_OUT1) of each window */
#define RSN_OUT1           352u
#define RSN_LOOKAHEAD      0u
#define RSN_RES_SCALE      19.6114101f

#define RSN_IN_SCALE       0.0133493869f
#define RSN_IN_ZP          (-1)
#define RSN_OUT_SCALE      0.0100028459f
#define RSN_OUT_ZP         (-77)
