/**
  ******************************************************************************
  * @file    network_ecblobs.h
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2024 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */


#ifdef __cplusplus
extern "C" {
#endif

#include "ll_aton_caches_interface.h"

#include <string.h>

#if !defined(ECBLOB_CONST_SECTION)
#define ECBLOB_CONST_SECTION /* Empty */
#endif
#if !defined(ECBLOB_RUNTIME_SECTION)
#define ECBLOB_RUNTIME_SECTION /* Empty */
#endif

/* relocated by gen_rsn_fw.py: 28608 B in NPU RAM */
#define _ec_blob_network_1_address ((uintptr_t)0x242168C0UL)

// this macro returns true if _ec_blob_network_1 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_1 false

// this function MUST be called ONLY ONCE once for initializing the network
bool LL_ATON_EC_Network_Init_network(void)
{
  return true;
}

// this function should be called before each inference
bool LL_ATON_EC_Inference_Init_network(void)
{
  return true;
}

#ifdef __cplusplus
}
#endif

