/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    network.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "6770925d2803cfc24528c45bb3ba8b791b2a83e4"
 * GIT_BRANCH      "HEAD"
 * GIT_DESCRIPTION "atonn-v1.1.3-275-g6770925d2"
 *
 * Command Line options:
 * --load-mdesc-file = "/Applications/ST/STEdgeAI/4.0/Utilities/configs/stm32n6"
 * --load-cdesc-file = "/Applications/ST/STEdgeAI/4.0/Utilities/configs/cortex-m55"
 * --load-mpool-file = "/Users/sheramirdullat/Developer/NeuralAutoTune/RSN/tools/swiftf0/st_ai_ws/stm32n6_sf0"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "/Users/sheramirdullat/Developer/NeuralAutoTune/RSN/tools/swiftf0/npu_build/swiftf0_int8_phasegrid_Q.json"
 * --Os = true
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "/Users/sheramirdullat/Developer/NeuralAutoTune/RSN/tools/swiftf0/npu_build/swiftf0_int8_phasegrid.onnx"
 * --out-dir-prefix = "/var/folders/xf/_jysnv0j7r33kp_9fdpptv9m0000gn/T/tmp.v5Y68ODfFY/neural_art__network/"
 * --network-name = "network"
 * --generate-stai = true
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = true
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"
#include "ll_aton_cipher.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 3 || LL_ATON_VERSION_DEV != 275
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 7 is 90.16 KB */
/* index=7 file postfix=AXISRAM3 name=npuRAM3 offset=0x24200000  absolute_mode size=458744 READ_ONLY THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=YES score=62  */
/* global pool 8 is ? */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  absolute_mode size=0 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
/* global pool 6 is ? */
/* index=6 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 1 is 112.50 KB */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x242e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x24350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x24270000  absolute_mode size=0 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 11 is 112.50 KB */
/* index=11 file postfix=AXISRAM5_AXISRAM6 name=npuRAM5_npuRAM6 offset=0x242e0000  absolute_mode size=917496 vpool READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=93  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM2 name=cpuRAM2 offset=0x24100000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM1 name=cpuRAM1 offset=0x24064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXIFLEXMEM name=flexMEM offset=0x24000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */


const LL_Streng_EncryptionTypedef *LL_ATON_WeightEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

const LL_Streng_EncryptionTypedef *LL_ATON_BlobEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

#include "network_ecblobs.h"

/* scheduling epoch=0    nodes=40  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_network_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_network_1') start function
static void _ec_blob_cache_start_func_1(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance) {
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x242e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x242e0000UL + 32))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x242e0000UL + 0))) /* Equivalent hex address = 0x242e0000UL */, 32);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x242e0000UL + 28800))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x242e0000UL + 29280))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x242e0000UL + 28800))) /* Equivalent hex address = 0x242e7080UL */, 480);

};


/* scheduling DONE                 ------------------------------------------------------------------- */

const LL_ATON_RT_EpochBlockItem_t *LL_ATON_EpochBlockItems_network(void) {

  static const LL_ATON_RT_EpochBlockItem_t ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_network_1_address),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 27,
      .estimated_npu_cycles = 571211,
      .estimated_tot_cycles = 830420,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_1_480_1[] = { 1, 480, 1, 1 };
  static const uint32_t buff_info__mem_shape_F_1_1_480_1[] = { 1, 1, 480, 1 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.00784313771873713 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -1 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_60_1_1_5[] = { 60, 1, 5, 1 };
  static const uint32_t buff_info__mem_shape_F_60_1_1_5[] = { 60, 1, 1, 5 };
  static const float buff_info_Conv2D_3_weights_quant_scale[] = { 0.0317816622555256, 0.00765854958444834, 0.034331314265728, 0.00699345860630274, 0.00537474965676665, 0.0521041750907898, 0.0454888716340065, 0.0122589319944382, 0.0342371836304665, 0.00961390044540167, 0.0051816669292748, 0.0215002372860909, 0.00727683212608099, 0.0156046953052282, 0.0442372784018517, 0.00909655261784792, 0.0348260030150414, 0.012375014834106, 0.0474323444068432, 0.0104355793446302, 0.0627754479646683, 0.0767843723297119, 0.114540196955204, 0.0233708433806896, 0.00521332025527954, 0.00736426888033748, 0.0380227155983448, 0.0154941799119115, 0.0544890873134136, 0.00542107550427318, 0.00795975513756275, 0.00705978693440557, 0.0393693819642067, 0.00657322769984603, 0.0862624421715736, 0.0125223603099585, 0.0574209168553352, 0.0790394023060799, 0.163427114486694, 0.136378735303879, 0.0708189979195595, 0.0470823049545288, 0.0443217307329178, 0.153243765234947, 0.0132625428959727, 0.0401223190128803, 0.00948845501989126, 0.00695162685588002, 0.00618360564112663, 0.055232398211956, 0.0332470573484898, 0.0121772857382894, 0.013669990003109, 0.0201853811740875, 0.00870683882385492, 0.0387793146073818, 0.0795878320932388, 0.0787757411599159, 0.00465386267751455, 0.00848023965954781 };
  static const int16_t buff_info_Conv2D_3_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1_60_1_1[] = { 1, 1, 1, 60 };
  static const uint32_t buff_info__mem_shape_M20_1_60_1_1[] = { 1, 3, 1, 1, 20 };
  static const float buff_info_Conv2D_32_weights_quant_scale[] = { 0.00638795224949718 };
  static const int16_t buff_info_Conv2D_32_weights_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_32_60_1_1[] = { 32, 1, 1, 60 };
  static const uint32_t buff_info__mem_shape_F_32_60_1_1[] = { 32, 60, 1, 1 };
  static const float buff_info_Gemm_47_weights_transposed_3_quant_scale[] = { 0.0011299567995593, 0.00277828006073833, 0.00106975727248937, 0.00361029128544033, 0.000990083790384233, 0.00417569139972329, 0.00392120936885476, 0.00303156906738877, 0.0027388702146709, 0.00310653285123408, 0.00100955250672996, 0.00112151424400508, 0.00364112248644233, 0.00101291749160737, 0.00379886059090495, 0.00265229307115078, 0.00107508199289441, 0.00112425803672522, 0.00300130061805248, 0.00107943720649928, 0.00667749624699354, 0.00101574650034308, 0.00275345169939101, 0.00117596576455981, 0.00318084051832557, 0.00250197178684175, 0.00278927478939295, 0.00333235715515912, 0.00232322397641838, 0.00100940652191639, 0.00358588900417089, 0.00294001121073961 };
  static const int16_t buff_info_Gemm_47_weights_transposed_3_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1_32_1_1[] = { 1, 1, 1, 32 };
  static const uint32_t buff_info__mem_shape_F_1_32_1_1[] = { 1, 32, 1, 1 };
  static const float buff_info_Gemm_51_weights_transposed_9_quant_scale[] = { 0.00761904288083315 };
  static const int16_t buff_info_Gemm_51_weights_transposed_9_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_60_60_3_1[] = { 60, 3, 1, 60 };
  static const uint32_t buff_info__mem_shape_M15_60_60_3_1[] = { 60, 4, 3, 1, 15 };
  static const float buff_info_Conv2D_8_weights_submask_0_0_0_0_60_60_3_1_94_quant_scale[] = { 0.000863188237417489, 0.00121360807679594, 0.000885882647708058, 0.000940969213843346, 0.000595294230151922, 0.0012730733724311, 0.000502166629303247, 0.00121388281695545, 0.000485149794258177, 0.000475875625852495, 0.0018088665092364, 0.00131941738072783, 0.00053780508460477, 0.000925523287151009, 0.00196485198102891, 0.000652239250484854, 0.000559092732146382, 0.00108954624738544, 0.000599007587879896, 0.000574276607949287, 0.000355342053808272, 0.000600813305936754, 0.000621206185314804, 0.00133027660194784, 0.00221525691449642, 0.000941031496040523, 0.000657612574286759, 0.000672828697133809, 0.000739248818717897, 0.00173639669083059, 0.00163010705728084, 0.000920582097023726, 0.000601306732278317, 0.00116926152259111, 0.000894495227839798, 0.000730815110728145, 0.000774478714447469, 0.00105309067294002, 0.00094058841932565, 0.000912713992875069, 0.000542944646440446, 0.000626360822934657, 0.00118912407197058, 0.00134131161030382, 0.000570006552152336, 0.000905875756870955, 0.000969743821769953, 0.000991491018794477, 0.000624503067228943, 0.00261657335795462, 0.00110783847048879, 0.000969568500295281, 0.000730042462237179, 0.00330096273683012, 0.00154689571354538, 0.000708400271832943, 0.00156032235827297, 0.00045977983972989, 0.00152157293632627, 0.00124678330030292 };
  static const int16_t buff_info_Conv2D_8_weights_submask_0_0_0_0_60_60_3_1_94_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_60_60_2_1[] = { 60, 2, 1, 60 };
  static const uint32_t buff_info__mem_shape_M15_60_60_2_1[] = { 60, 4, 2, 1, 15 };
  static const float buff_info_Conv2D_8_weights_submask_0_0_3_0_60_60_2_1_95_quant_scale[] = { 0.000863188237417489, 0.00121360807679594, 0.000885882647708058, 0.000940969213843346, 0.000595294230151922, 0.0012730733724311, 0.000502166629303247, 0.00121388281695545, 0.000485149794258177, 0.000475875625852495, 0.0018088665092364, 0.00131941738072783, 0.00053780508460477, 0.000925523287151009, 0.00196485198102891, 0.000652239250484854, 0.000559092732146382, 0.00108954624738544, 0.000599007587879896, 0.000574276607949287, 0.000355342053808272, 0.000600813305936754, 0.000621206185314804, 0.00133027660194784, 0.00221525691449642, 0.000941031496040523, 0.000657612574286759, 0.000672828697133809, 0.000739248818717897, 0.00173639669083059, 0.00163010705728084, 0.000920582097023726, 0.000601306732278317, 0.00116926152259111, 0.000894495227839798, 0.000730815110728145, 0.000774478714447469, 0.00105309067294002, 0.00094058841932565, 0.000912713992875069, 0.000542944646440446, 0.000626360822934657, 0.00118912407197058, 0.00134131161030382, 0.000570006552152336, 0.000905875756870955, 0.000969743821769953, 0.000991491018794477, 0.000624503067228943, 0.00261657335795462, 0.00110783847048879, 0.000969568500295281, 0.000730042462237179, 0.00330096273683012, 0.00154689571354538, 0.000708400271832943, 0.00156032235827297, 0.00045977983972989, 0.00152157293632627, 0.00124678330030292 };
  static const int16_t buff_info_Conv2D_8_weights_submask_0_0_3_0_60_60_2_1_95_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_13_weights_submask_0_0_0_0_60_60_3_1_96_quant_scale[] = { 0.00109954725485295, 0.00125574402045459, 0.00229750759899616, 0.00201097456738353, 0.000891979492735118, 0.00152927718590945, 0.000636488024611026, 0.000943783379625529, 0.00142011675052345, 0.00142207043245435, 0.001572783337906, 0.000826101342681795, 0.000886055815499276, 0.00136211141943932, 0.00156359409447759, 0.00160993926692754, 0.00104796630330384, 0.000993309658952057, 0.00133111723698676, 0.000928679946810007, 0.00104695139452815, 0.00128631363622844, 0.000828127784188837, 0.00137987511698157, 0.00174594589043409, 0.00107360712718219, 0.00145850807894021, 0.00126231799367815, 0.00159215205349028, 0.00142911321017891, 0.00125726475380361, 0.000694311107508838, 0.00215655844658613, 0.00209475867450237, 0.000822686066385359, 0.00133759796153754, 0.00174084852915257, 0.00171594298444688, 0.00083807494957, 0.0015458621783182, 0.000878277234733105, 0.00170397199690342, 0.00140397530049086, 0.00103442557156086, 0.000796315202023834, 0.00260175066068769, 0.000881379586644471, 0.000697398849297315, 0.00128337764181197, 0.00234122527763247, 0.000935697637032717, 0.00161071727052331, 0.00121630169451237, 0.001033736160025, 0.00132183125242591, 0.000923008017707616, 0.00105208065360785, 0.00152667018119246, 0.00139514089096338, 0.00139812042471021 };
  static const int16_t buff_info_Conv2D_13_weights_submask_0_0_0_0_60_60_3_1_96_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_13_weights_submask_0_0_3_0_60_60_2_1_97_quant_scale[] = { 0.00109954725485295, 0.00125574402045459, 0.00229750759899616, 0.00201097456738353, 0.000891979492735118, 0.00152927718590945, 0.000636488024611026, 0.000943783379625529, 0.00142011675052345, 0.00142207043245435, 0.001572783337906, 0.000826101342681795, 0.000886055815499276, 0.00136211141943932, 0.00156359409447759, 0.00160993926692754, 0.00104796630330384, 0.000993309658952057, 0.00133111723698676, 0.000928679946810007, 0.00104695139452815, 0.00128631363622844, 0.000828127784188837, 0.00137987511698157, 0.00174594589043409, 0.00107360712718219, 0.00145850807894021, 0.00126231799367815, 0.00159215205349028, 0.00142911321017891, 0.00125726475380361, 0.000694311107508838, 0.00215655844658613, 0.00209475867450237, 0.000822686066385359, 0.00133759796153754, 0.00174084852915257, 0.00171594298444688, 0.00083807494957, 0.0015458621783182, 0.000878277234733105, 0.00170397199690342, 0.00140397530049086, 0.00103442557156086, 0.000796315202023834, 0.00260175066068769, 0.000881379586644471, 0.000697398849297315, 0.00128337764181197, 0.00234122527763247, 0.000935697637032717, 0.00161071727052331, 0.00121630169451237, 0.001033736160025, 0.00132183125242591, 0.000923008017707616, 0.00105208065360785, 0.00152667018119246, 0.00139514089096338, 0.00139812042471021 };
  static const int16_t buff_info_Conv2D_13_weights_submask_0_0_3_0_60_60_2_1_97_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_18_weights_submask_0_0_0_0_60_60_3_1_98_quant_scale[] = { 0.00125691201537848, 0.00161539332475513, 0.00116818770766258, 0.000988112646155059, 0.00151131523307413, 0.00132175826001912, 0.00102560478262603, 0.00118747423402965, 0.000912596471607685, 0.00133436196483672, 0.0011490712640807, 0.00107404624577612, 0.00149954343214631, 0.00123134185560048, 0.00106335349846631, 0.00121788890101016, 0.00100716389715672, 0.00228380784392357, 0.00149622547905892, 0.00137813226319849, 0.0010979202343151, 0.000963518279604614, 0.00161645922344178, 0.00147778762038797, 0.00104884733445942, 0.00127186777535826, 0.00157703936565667, 0.00140922574792057, 0.00102465250529349, 0.00121329945977777, 0.00148809771053493, 0.00143392034806311, 0.00174635206349194, 0.00144775386434048, 0.00142281386069953, 0.0010886910604313, 0.0013957709306851, 0.00149647332727909, 0.00137432687915862, 0.00139333098195493, 0.00150569959077984, 0.00201497948728502, 0.00199927622452378, 0.00186584587208927, 0.000960264937020838, 0.0023723931517452, 0.00152983551379293, 0.00133701262529939, 0.00154623202979565, 0.00181656761560589, 0.0013643957208842, 0.00161844654940069, 0.00203243037685752, 0.00159713451284915, 0.00117544771637768, 0.00111902423668653, 0.00133847701363266, 0.00190408551134169, 0.00158189528156072, 0.00129711604677141 };
  static const int16_t buff_info_Conv2D_18_weights_submask_0_0_0_0_60_60_3_1_98_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_18_weights_submask_0_0_3_0_60_60_2_1_99_quant_scale[] = { 0.00125691201537848, 0.00161539332475513, 0.00116818770766258, 0.000988112646155059, 0.00151131523307413, 0.00132175826001912, 0.00102560478262603, 0.00118747423402965, 0.000912596471607685, 0.00133436196483672, 0.0011490712640807, 0.00107404624577612, 0.00149954343214631, 0.00123134185560048, 0.00106335349846631, 0.00121788890101016, 0.00100716389715672, 0.00228380784392357, 0.00149622547905892, 0.00137813226319849, 0.0010979202343151, 0.000963518279604614, 0.00161645922344178, 0.00147778762038797, 0.00104884733445942, 0.00127186777535826, 0.00157703936565667, 0.00140922574792057, 0.00102465250529349, 0.00121329945977777, 0.00148809771053493, 0.00143392034806311, 0.00174635206349194, 0.00144775386434048, 0.00142281386069953, 0.0010886910604313, 0.0013957709306851, 0.00149647332727909, 0.00137432687915862, 0.00139333098195493, 0.00150569959077984, 0.00201497948728502, 0.00199927622452378, 0.00186584587208927, 0.000960264937020838, 0.0023723931517452, 0.00152983551379293, 0.00133701262529939, 0.00154623202979565, 0.00181656761560589, 0.0013643957208842, 0.00161844654940069, 0.00203243037685752, 0.00159713451284915, 0.00117544771637768, 0.00111902423668653, 0.00133847701363266, 0.00190408551134169, 0.00158189528156072, 0.00129711604677141 };
  static const int16_t buff_info_Conv2D_18_weights_submask_0_0_3_0_60_60_2_1_99_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_23_weights_submask_0_0_0_0_60_60_3_1_100_quant_scale[] = { 0.00108681584242731, 0.00166801328305155, 0.00116561318282038, 0.0013819799060002, 0.00194133468903601, 0.00244017038494349, 0.00106315559241921, 0.00156887213233858, 0.00207211193628609, 0.00139553740154952, 0.00212652259506285, 0.00168817082885653, 0.00115945853758603, 0.00220761937089264, 0.00142297020647675, 0.00180849188473076, 0.0022163453977555, 0.00130687223281711, 0.00162074936088175, 0.00166259135585278, 0.00124627782497555, 0.00149977370165288, 0.00226733740419149, 0.00159234600141644, 0.00225595477968454, 0.00155056116636842, 0.00173708435613662, 0.00204469636082649, 0.00134621001780033, 0.0012307979632169, 0.00125012081116438, 0.00157267518807203, 0.00238428241573274, 0.00120561523362994, 0.00173003762029111, 0.00159263075329363, 0.00161853746976703, 0.00231932988390326, 0.00137588544748724, 0.00128527800552547, 0.00192744995001704, 0.00157855520956218, 0.00237233773805201, 0.00139742391183972, 0.00218488671816885, 0.001739980885759, 0.00120101612992585, 0.00127032794989645, 0.00163827452342957, 0.00148183549754322, 0.00140493037179112, 0.00200932915322483, 0.00222509121522307, 0.00116628268733621, 0.00187777506653219, 0.00159266823902726, 0.00192127819173038, 0.00202583079226315, 0.0015049249632284, 0.00164863665122539 };
  static const int16_t buff_info_Conv2D_23_weights_submask_0_0_0_0_60_60_3_1_100_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_23_weights_submask_0_0_3_0_60_60_2_1_101_quant_scale[] = { 0.00108681584242731, 0.00166801328305155, 0.00116561318282038, 0.0013819799060002, 0.00194133468903601, 0.00244017038494349, 0.00106315559241921, 0.00156887213233858, 0.00207211193628609, 0.00139553740154952, 0.00212652259506285, 0.00168817082885653, 0.00115945853758603, 0.00220761937089264, 0.00142297020647675, 0.00180849188473076, 0.0022163453977555, 0.00130687223281711, 0.00162074936088175, 0.00166259135585278, 0.00124627782497555, 0.00149977370165288, 0.00226733740419149, 0.00159234600141644, 0.00225595477968454, 0.00155056116636842, 0.00173708435613662, 0.00204469636082649, 0.00134621001780033, 0.0012307979632169, 0.00125012081116438, 0.00157267518807203, 0.00238428241573274, 0.00120561523362994, 0.00173003762029111, 0.00159263075329363, 0.00161853746976703, 0.00231932988390326, 0.00137588544748724, 0.00128527800552547, 0.00192744995001704, 0.00157855520956218, 0.00237233773805201, 0.00139742391183972, 0.00218488671816885, 0.001739980885759, 0.00120101612992585, 0.00127032794989645, 0.00163827452342957, 0.00148183549754322, 0.00140493037179112, 0.00200932915322483, 0.00222509121522307, 0.00116628268733621, 0.00187777506653219, 0.00159266823902726, 0.00192127819173038, 0.00202583079226315, 0.0015049249632284, 0.00164863665122539 };
  static const int16_t buff_info_Conv2D_23_weights_submask_0_0_3_0_60_60_2_1_101_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_28_weights_submask_0_0_0_0_60_60_3_1_102_quant_scale[] = { 0.00181530718691647, 0.0015229934360832, 0.00149049423635006, 0.0029872755985707, 0.00360280042514205, 0.00420160405337811, 0.00360238598659635, 0.00226470385678113, 0.00402709003537893, 0.00393146136775613, 0.00230282451957464, 0.0012146111112088, 0.00331162032671273, 0.00157845322974026, 0.00427155289798975, 0.00300176301971078, 0.0019806488417089, 0.0025330875068903, 0.00141217710915953, 0.00218182150274515, 0.00222287699580193, 0.00291475490666926, 0.00297194998711348, 0.00281357392668724, 0.00468521052971482, 0.00410982174798846, 0.00267950189299881, 0.0055055133998394, 0.0024029107298702, 0.00330268871039152, 0.00357742514461279, 0.00231475522741675, 0.0026398841291666, 0.00252239126712084, 0.00138204416725785, 0.00316528952680528, 0.00487921899184585, 0.00310749839991331, 0.00366404512897134, 0.00393817480653524, 0.00286892638541758, 0.00182932871393859, 0.00135603116359562, 0.00247052521444857, 0.00265362928621471, 0.00125634227879345, 0.00150233355816454, 0.00247446750290692, 0.00275817955844104, 0.00359130138531327, 0.00371610186994076, 0.00236591883003712, 0.00381475873291492, 0.00556252058595419, 0.00416585663333535, 0.00670009246096015, 0.00149275246076286, 0.00236681732349098, 0.00325960270129144, 0.00291396770626307 };
  static const int16_t buff_info_Conv2D_28_weights_submask_0_0_0_0_60_60_3_1_102_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const float buff_info_Conv2D_28_weights_submask_0_0_3_0_60_60_2_1_103_quant_scale[] = { 0.00181530718691647, 0.0015229934360832, 0.00149049423635006, 0.0029872755985707, 0.00360280042514205, 0.00420160405337811, 0.00360238598659635, 0.00226470385678113, 0.00402709003537893, 0.00393146136775613, 0.00230282451957464, 0.0012146111112088, 0.00331162032671273, 0.00157845322974026, 0.00427155289798975, 0.00300176301971078, 0.0019806488417089, 0.0025330875068903, 0.00141217710915953, 0.00218182150274515, 0.00222287699580193, 0.00291475490666926, 0.00297194998711348, 0.00281357392668724, 0.00468521052971482, 0.00410982174798846, 0.00267950189299881, 0.0055055133998394, 0.0024029107298702, 0.00330268871039152, 0.00357742514461279, 0.00231475522741675, 0.0026398841291666, 0.00252239126712084, 0.00138204416725785, 0.00316528952680528, 0.00487921899184585, 0.00310749839991331, 0.00366404512897134, 0.00393817480653524, 0.00286892638541758, 0.00182932871393859, 0.00135603116359562, 0.00247052521444857, 0.00265362928621471, 0.00125634227879345, 0.00150233355816454, 0.00247446750290692, 0.00275817955844104, 0.00359130138531327, 0.00371610186994076, 0.00236591883003712, 0.00381475873291492, 0.00556252058595419, 0.00416585663333535, 0.00670009246096015, 0.00149275246076286, 0.00236681732349098, 0.00325960270129144, 0.00291396770626307 };
  static const int16_t buff_info_Conv2D_28_weights_submask_0_0_3_0_60_60_2_1_103_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x242e0000UL) /* Equivalent hex address = 0x242e0000UL */},
      .offset_start = 0,
      .offset_end = 480,
      .offset_limit = 544,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_1_480_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1_480_1,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Conv2D_3_weights",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 91920,
      .offset_end = 92220,
      .offset_limit = 92288,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_60_1_1_5,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_1_1_5,
      .per_channel = 1,
      .scale = buff_info_Conv2D_3_weights_quant_scale,
      .offset = buff_info_Conv2D_3_weights_quant_offset,
    },
    {
      .name = "Conv2D_32_weights",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 92224,
      .offset_end = 92284,
      .offset_limit = 92352,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 20,
      .mem_shape = buff_info__mem_shape_M20_1_60_1_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_60_1_1,
      .per_channel = 0,
      .scale = buff_info_Conv2D_32_weights_quant_scale,
      .offset = buff_info_Conv2D_32_weights_quant_offset,
    },
    {
      .name = "Gemm_47_weights_transposed_3",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 90000,
      .offset_end = 91920,
      .offset_limit = 91984,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 60,
      .mem_shape = buff_info__mem_shape_F_32_60_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_60_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_47_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_47_weights_transposed_3_quant_offset,
    },
    {
      .name = "Gemm_51_weights_transposed_9",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 92288,
      .offset_end = 92321,
      .offset_limit = 92392,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 32,
      .mem_shape = buff_info__mem_shape_F_1_32_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_51_weights_transposed_9_quant_scale,
      .offset = buff_info_Gemm_51_weights_transposed_9_quant_offset,
    },
    {
      .name = "Conv2D_8_weights_submask_0_0_0_0_60_60_3_1_94",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 0,
      .offset_end = 10800,
      .offset_limit = 10864,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_3_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_submask_0_0_0_0_60_60_3_1_94_quant_scale,
      .offset = buff_info_Conv2D_8_weights_submask_0_0_0_0_60_60_3_1_94_quant_offset,
    },
    {
      .name = "Conv2D_8_weights_submask_0_0_3_0_60_60_2_1_95",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 54000,
      .offset_end = 61200,
      .offset_limit = 61264,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_2_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_2_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_submask_0_0_3_0_60_60_2_1_95_quant_scale,
      .offset = buff_info_Conv2D_8_weights_submask_0_0_3_0_60_60_2_1_95_quant_offset,
    },
    {
      .name = "Conv2D_13_weights_submask_0_0_0_0_60_60_3_1_96",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 10800,
      .offset_end = 21600,
      .offset_limit = 21664,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_3_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_13_weights_submask_0_0_0_0_60_60_3_1_96_quant_scale,
      .offset = buff_info_Conv2D_13_weights_submask_0_0_0_0_60_60_3_1_96_quant_offset,
    },
    {
      .name = "Conv2D_13_weights_submask_0_0_3_0_60_60_2_1_97",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 61200,
      .offset_end = 68400,
      .offset_limit = 68464,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_2_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_2_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_13_weights_submask_0_0_3_0_60_60_2_1_97_quant_scale,
      .offset = buff_info_Conv2D_13_weights_submask_0_0_3_0_60_60_2_1_97_quant_offset,
    },
    {
      .name = "Conv2D_18_weights_submask_0_0_0_0_60_60_3_1_98",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 21600,
      .offset_end = 32400,
      .offset_limit = 32464,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_3_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_18_weights_submask_0_0_0_0_60_60_3_1_98_quant_scale,
      .offset = buff_info_Conv2D_18_weights_submask_0_0_0_0_60_60_3_1_98_quant_offset,
    },
    {
      .name = "Conv2D_18_weights_submask_0_0_3_0_60_60_2_1_99",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 68400,
      .offset_end = 75600,
      .offset_limit = 75664,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_2_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_2_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_18_weights_submask_0_0_3_0_60_60_2_1_99_quant_scale,
      .offset = buff_info_Conv2D_18_weights_submask_0_0_3_0_60_60_2_1_99_quant_offset,
    },
    {
      .name = "Conv2D_23_weights_submask_0_0_0_0_60_60_3_1_100",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 32400,
      .offset_end = 43200,
      .offset_limit = 43264,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_3_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_23_weights_submask_0_0_0_0_60_60_3_1_100_quant_scale,
      .offset = buff_info_Conv2D_23_weights_submask_0_0_0_0_60_60_3_1_100_quant_offset,
    },
    {
      .name = "Conv2D_23_weights_submask_0_0_3_0_60_60_2_1_101",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 75600,
      .offset_end = 82800,
      .offset_limit = 82864,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_2_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_2_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_23_weights_submask_0_0_3_0_60_60_2_1_101_quant_scale,
      .offset = buff_info_Conv2D_23_weights_submask_0_0_3_0_60_60_2_1_101_quant_offset,
    },
    {
      .name = "Conv2D_28_weights_submask_0_0_0_0_60_60_3_1_102",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 43200,
      .offset_end = 54000,
      .offset_limit = 54064,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_3_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_28_weights_submask_0_0_0_0_60_60_3_1_102_quant_scale,
      .offset = buff_info_Conv2D_28_weights_submask_0_0_0_0_60_60_3_1_102_quant_offset,
    },
    {
      .name = "Conv2D_28_weights_submask_0_0_3_0_60_60_2_1_103",
      .addr_base = {(unsigned char *)(0x24200000UL) /* Equivalent hex address = 0x24200000UL */},
      .offset_start = 82800,
      .offset_end = 90000,
      .offset_limit = 90064,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 15,
      .mem_shape = buff_info__mem_shape_M15_60_60_2_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_60_60_2_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_28_weights_submask_0_0_3_0_60_60_2_1_103_quant_scale,
      .offset = buff_info_Conv2D_28_weights_submask_0_0_3_0_60_60_2_1_103_quant_offset,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1_1[] = { 1, 1 };
  static const float buff_info_Quantize_52_out_0_quant_scale[] = { 0.0574029013514519 };
  static const int16_t buff_info_Quantize_52_out_0_quant_offset[] = { -90 };
  static const uint32_t buff_info__shape_1_360[] = { 1, 1, 360, 1 };
  static const uint32_t buff_info__mem_shape_U_1_360[] = { 1, 360 };
  static const float buff_info_Quantize_42_out_0_quant_scale[] = { 0.117495745420456 };
  static const int16_t buff_info_Quantize_42_out_0_quant_offset[] = { 16 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_52_out_0",
      .addr_base = {(unsigned char *)(0x242e0000UL) /* Equivalent hex address = 0x242e0000UL */},
      .offset_start = 0,
      .offset_end = 1,
      .offset_limit = 72,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 26,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_1,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1,
      .per_channel = 0,
      .scale = buff_info_Quantize_52_out_0_quant_scale,
      .offset = buff_info_Quantize_52_out_0_quant_offset,
    },
    {
      .name = "Quantize_42_out_0",
      .addr_base = {(unsigned char *)(0x242e0000UL) /* Equivalent hex address = 0x242e0000UL */},
      .offset_start = 28800,
      .offset_end = 29160,
      .offset_limit = 29224,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 26,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_360,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_360,
      .per_channel = 0,
      .scale = buff_info_Quantize_42_out_0_quant_scale,
      .offset = buff_info_Quantize_42_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_network(void)
{
  return NULL;
}

