"""Write the pitch network's firmware files from an epoch-controller build.

    python3 tools/board/gen_sf0_fw.py --gen tools/swiftf0/npu_build_ec

Writes network.c, network_ecblobs.h and swiftf0_weights.c into
AppliNonSecure/X-CUBE-AI/network. At boot sf0_npu_init() copies the weights to
AXISRAM3 and the blob right after them.

Copyright 2026 Sher Amir Singh Dullat
SPDX-License-Identifier: Apache-2.0
"""
import argparse
import re
import shutil
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_rsn_fw import relocate_ecblobs  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
NET = ROOT / "AppliNonSecure/X-CUBE-AI/network"
W_ADDR = 0x24200000          # AXISRAM3
W_BANK = 0x70000


def c_bytes(b: bytes, per=29):
    rows = [",".join(str(x) for x in b[i:i + per]) for i in range(0, len(b), per)]
    return ",\n  ".join(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen", required=True)
    gen = Path(ap.parse_args().gen)

    w = (gen / "atonbuf.AXISRAM3.raw").read_bytes()
    hdr, blob, blobs = relocate_ecblobs((gen / "network_ecblobs.h").read_text(), W_ADDR + len(w))
    assert len(blobs) == 1, blobs
    name, b_addr, b_len = blobs[0]
    assert b_addr + b_len <= W_ADDR + W_BANK, "weights + blob exceed AXISRAM3"
    blob = blob[b_addr - (W_ADDR + len(w)):]          # drop the padding

    for f, bak in (("network.c", "network.c.plain-bak"), ("swiftf0_weights.c", "swiftf0_weights.c.plain-bak")):
        if not (NET / bak).exists():
            shutil.copy(NET / f, NET / bak)
    shutil.copy(gen / "network.c", NET / "network.c")
    (NET / "network_ecblobs.h").write_text(hdr)

    (NET / "swiftf0_weights.c").write_text(f"""/*
 * swiftf0_weights.c - generated by tools/board/gen_sf0_fw.py, do not edit
 *
 * sf0_npu_init() copies the weights to 0x{W_ADDR:08X} and the epoch-controller
 * blob to 0x{b_addr:08X}.
 */
#include <stdint.h>

const uint32_t  sf0_npu_weights_len  = {len(w)}u;
const uintptr_t sf0_npu_weights_addr = 0x{W_ADDR:08X}UL;
const uint8_t   sf0_npu_weights[{len(w)}] = {{
  {c_bytes(w)}
}};

const uint32_t  sf0_npu_ecblob_len  = {b_len}u;
const uintptr_t sf0_npu_ecblob_addr = 0x{b_addr:08X}UL;
__attribute__((aligned(8)))
const uint8_t   sf0_npu_ecblob[{b_len}] = {{
  {c_bytes(blob)}
}};
""")
    print(f"network.c + network_ecblobs.h ({name} -> 0x{b_addr:08X}, {b_len} B) + "
          f"swiftf0_weights.c (weights {len(w)} B @ 0x{W_ADDR:08X}) -> {NET}")


if __name__ == "__main__":
    main()
