"""Turn a deployed RSN package and its generated NPU code into firmware files.

    python3 tools/board/gen_rsn_fw.py --deploy deploy/rsn_final_v1 --gen <dir with rsn.c>

Writes rsn.c and rsn_ecblobs.h (X-CUBE-AI/network), rsn_meta.h, rsn_film.h and
rsn_golden.h (natune/src/npu), and tools/board/blobs/rsn_weights.bin, the NPU
RAM image (weights plus epoch-controller blob) that board.sh loads into
AXISRAM4.

Copyright 2026 Sher Amir Singh Dullat
SPDX-License-Identifier: Apache-2.0
"""
import argparse
import json
import re
import shutil
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NET = ROOT / "AppliNonSecure/X-CUBE-AI/network"
INC = ROOT / "AppliNonSecure/natune/src/npu"
BLOBS = ROOT / "tools/board/blobs"
W_ADDR = 0x24270000          # AXISRAM4
W_BANK = 0x70000             # 448 KB
EC_ALIGN = 64


def relocate_ecblobs(hdr: str, base: int):
    """Replace the blob arrays in an *_ecblobs.h with fixed addresses from `base` on.

    Returns (header, blob bytes, [(name, addr, nbytes)]).
    """
    pat = re.compile(r"ECBLOB_CONST_SECTION\s*\n(?://[^\n]*\n)?__attribute__\(\(aligned\(64\)\)\)\s*\n"
                     r"static const uint64_t (\w+)\[(\d+)\] =\s*\{(.*?)\};\s*\n", re.S)
    img, blobs, addr = b"", [], base
    for m in pat.finditer(hdr):
        name, n = m.group(1), int(m.group(2))
        words = [int(w.rstrip("UuLl"), 16) for w in re.findall(r"0x[0-9a-fA-F]+[uUlL]*", m.group(3))]
        # the declared size is rounded up; C zero-fills the rest
        assert len(words) <= n, f"{name}: parsed {len(words)} words, declared {n}"
        words += [0] * (n - len(words))
        pad = (-addr) % EC_ALIGN
        img += b"\0" * pad
        addr += pad
        data = struct.pack(f"<{n}Q", *words)
        blobs.append((name, addr, len(data)))
        img += data
        addr += len(data)
    assert blobs, "no EC blob arrays found in rsn_ecblobs.h"
    out = pat.sub("", hdr)
    for name, a, nb in blobs:
        out, k = re.subn(rf"#define {name}_address {name}\b",
                         f"/* relocated by gen_rsn_fw.py: {nb} B in NPU RAM */\n"
                         f"#define {name}_address ((uintptr_t)0x{a:08X}UL)", out)
        assert k == 1, f"no address define for {name}"
    return out, img, blobs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deploy", required=True)
    ap.add_argument("--gen", required=True)
    a = ap.parse_args()
    dep, gen = Path(a.deploy), Path(a.gen)
    meta = json.loads((dep / "rsn_deploy.json").read_text())

    stub = NET / "rsn.c"
    if stub.exists() and not (NET / "rsn.c.b2stub-bak").exists():
        shutil.copy(stub, NET / "rsn.c.b2stub-bak")
    shutil.copy(gen / "rsn.c", NET / "rsn.c")

    w = (gen / "atonbuf.AXISRAM4.raw").read_bytes()
    img, blobs = w, []
    ech = gen / "rsn_ecblobs.h"
    if ech.exists():
        hdr, ec, blobs = relocate_ecblobs(ech.read_text(), W_ADDR + len(w))
        img = w + ec
        (NET / "rsn_ecblobs.h").write_text(hdr)
    elif (NET / "rsn_ecblobs.h").exists():
        (NET / "rsn_ecblobs.h").unlink()
    assert len(img) <= W_BANK, f"NPU-RAM image {len(img)} B > AXISRAM4"
    crc = zlib.crc32(img) & 0xFFFFFFFF
    BLOBS.mkdir(parents=True, exist_ok=True)
    (BLOBS / "rsn_weights.bin").write_bytes(img)
    (BLOBS / "rsn_weights.addr").write_text(f"0x{W_ADDR:08X}\n")
    ec_note = "".join(f" *   EC blob {nm}: 0x{a:08X}, {nb} B\n" for nm, a, nb in blobs)

    for f in ("rsn_film.h", "rsn_golden.h"):
        shutil.copy(dep / f, INC / f)

    iq, oq = meta["input_quant"], meta["output_dequant"]
    o0, o1 = meta["output_slice"]
    (INC / "rsn_meta.h").write_text(f"""/* rsn_meta.h - generated by tools/board/gen_rsn_fw.py, do not edit
 * source: {dep} ({meta.get('checkpoint')}, step {meta.get('step')}, qat={meta.get('qat')})
 * arch  : {meta['arch']}
 */
#pragma once
#include <stdint.h>

/* The NPU RAM image is loaded by tools/board/board.sh from
 * tools/board/blobs/rsn_weights.bin; rsn_npu_init() checks its CRC.
 *   weights: {len(w)} B
{ec_note} */
#define RSN_WEIGHTS_ADDR   0x{W_ADDR:08X}UL
#define RSN_WEIGHTS_LEN    {len(img)}u      /* whole image: weights{' + EC blobs' if blobs else ''} */
#define RSN_WEIGHTS_CRC32  0x{crc:08X}u
#define RSN_EC             {1 if blobs else 0}u        /* 1: epoch-controller build (needs LL_ATON_RT_MODE=2) */

#define RSN_WINDOW         {meta['window']}u
#define RSN_HOP            {meta['hop']}u
#define RSN_CH_IN          {meta['input_channels']}u
#define RSN_OUT0           {o0}u        /* keep outputs [RSN_OUT0, RSN_OUT1) of each window */
#define RSN_OUT1           {o1}u
#define RSN_LOOKAHEAD      {meta['lookahead_samples']}u
#define RSN_RES_SCALE      {meta['res_scale']:.9g}f

#define RSN_IN_SCALE       {iq['scale']:.9g}f
#define RSN_IN_ZP          ({iq['zero_point']})
#define RSN_OUT_SCALE      {oq['scale']:.9g}f
#define RSN_OUT_ZP         ({oq['zero_point']})
""")
    print(f"rsn.c -> {NET/'rsn.c'}")
    print(f"NPU-RAM image {len(img)} B (weights {len(w)}"
          + "".join(f" + {nm} {nb} @0x{a:08X}" for nm, a, nb in blobs)
          + f"), CRC32 0x{crc:08X} -> {BLOBS/'rsn_weights.bin'} @ 0x{W_ADDR:08X}")
    print(f"headers -> {INC}/rsn_meta.h, rsn_film.h, rsn_golden.h")


if __name__ == "__main__":
    main()
