"""Package an exported RSN for the firmware: INT8 graph, FiLM inputs and golden
vectors for the boot self-test.

    python -m rsn.package --ckpt <ckpt> --int8 <rsn_int8.onnx> --out <dir>

Copyright 2026 Sher Amir Singh Dullat
SPDX-License-Identifier: Apache-2.0
"""

from __future__ import annotations

import argparse
import datetime
import json
import shutil
from pathlib import Path

import numpy as np
import torch

from . import dsp
from .model import CH, CIN, EMB, WINDOW, from_arch, output_slice


def _q_params(onnx_path):
    import onnx
    from onnx import numpy_helper
    m = onnx.load(onnx_path)
    init = {i.name: numpy_helper.to_array(i) for i in m.graph.initializer}
    ins = {i.name for i in m.graph.input} - set(init)
    q = {}
    for n in m.graph.node:
        if n.op_type == "QuantizeLinear" and n.input[0] in ins:
            q[n.input[0]] = (float(init[n.input[1]]), int(init[n.input[2]]))
    out = m.graph.output[0].name
    dq = next(n for n in m.graph.node if out in n.output)
    q[out] = (float(init[dq.input[1]]), int(init[dq.input[2]]))
    return q


def _c_array(name, vals, ctype, fmt):
    body = ", ".join(fmt.format(v) for v in vals)
    return f"static const {ctype} {name}[{len(vals)}] = {{ {body} }};\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--int8", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--emb", choices=("mean",), default="mean")
    ap.add_argument("--cache", default=None,
                    help="with a cache: also write golden vectors (real windows -> the INT8 "
                         "graph's exact output) for the on-board self-test")
    ap.add_argument("--golden-n", dest="golden_n", type=int, default=8)
    ap.add_argument("--emb-json", dest="emb_json", default=None,
                    help="an embedding from rsn.calibrate --out (overrides --emb)")
    a = ap.parse_args()

    ck = torch.load(a.ckpt, map_location="cpu", weights_only=False)
    model = from_arch(ck.get("arch"), ck["n_emb"]).eval()
    model.load_state_dict(ck["model"])
    L = model.lookahead
    o0, o1 = output_slice(L)
    meta = ck.get("meta", {})
    res_scale = float(meta.get("res_scale", dsp.RES_SCALE))

    if a.emb_json:
        cj = json.loads(Path(a.emb_json).read_text())
        e = torch.tensor(cj["vector"], dtype=torch.float32)
        emb_src = f"calibrated for {cj.get('singer')} ({a.emb_json})"
    else:
        e = model.emb.weight.detach().mean(0)
        emb_src = f"mean of the trained table ({model.emb.weight.shape[0]} rows)"
    with torch.no_grad():
        film = []
        for i, f in enumerate(model.films):
            film.append((f"rsn_gamma{i}", f.gamma(e[None]).view(-1).numpy()))
            film.append((f"rsn_delta{i}", f.delta(e[None]).view(-1).numpy()))

    q = _q_params(a.int8)
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    shutil.copy(a.int8, out / "rsn_int8.onnx")

    h = ["/* rsn_film.h - generated by rsn.package, do not edit\n"
         f" * FiLM inputs for: {emb_src}\n"
         f" * checkpoint: {a.ckpt}\n"
         " * Feed each as its NPU input tensor [1,96,1,1]. The _q8 arrays are already\n"
         " * quantized with the INT8 graph's own input scale/zero-point. */\n",
         "#pragma once\n#include <stdint.h>\n\n",
         f"#define RSN_N_FILM {len(film)}\n#define RSN_CH {CH}\n\n"]
    for name, v in film:
        s, z = q[name]
        v8 = np.clip(np.round(v / s) + z, -128, 127).astype(np.int8)
        h.append(f"/* {name}: scale {s:.9g}, zero_point {z} */\n")
        h.append(_c_array(f"{name}_f32", v, "float", "{:.9g}f"))
        h.append(_c_array(f"{name}_q8", v8, "int8_t", "{:d}"))
        h.append("\n")
    (out / "rsn_film.h").write_text("".join(h))

    si, zi = q["rsn_in"]
    so, zo = q[next(k for k in q if k not in ("rsn_in",) and not k.startswith("rsn_gamma")
                    and not k.startswith("rsn_delta"))]
    dep = {
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
        "checkpoint": str(a.ckpt), "step": ck.get("step"),
        "val_rho": ck.get("val_rho"),
        "qat": bool(ck.get("qat")),
        "arch": model.arch(),
        "window": WINDOW, "hop": dsp.HOP, "input_channels": CIN,
        "input_layout": "NCHW [1,4,1,352]: ch0 excitation (unit RMS polyBLEP saw), "
                        "ch1 LPC residual x RES_SCALE, ch2 log2(F0_auth/440)/3, "
                        "ch3 log2(F0_corr/440)/3 -- each a contiguous 352-sample plane",
        "res_scale": res_scale,
        "output_slice": [o0, o1],
        "output_note": "keep outputs [o0, o1) of each 352 window; divide by res_scale",
        "lookahead_samples": L, "lookahead_ms": L / 16.0,
        "d_path_increment_48k": 3 * L,
        "input_quant": {"scale": si, "zero_point": zi},
        "output_dequant": {"scale": so, "zero_point": zo},
        "film_quant": {n: {"scale": q[n][0], "zero_point": q[n][1]} for n, _ in film},
        "embedding": {"source": emb_src, "vector": e.tolist()},
    }
    (out / "rsn_deploy.json").write_text(json.dumps(dep, indent=1))

    if a.cache:
        import onnx
        import onnxruntime as ort
        from .export import real_windows
        _m = onnx.load(str(out / "rsn_int8.onnx"))
        _used = {n.domain for n in _m.graph.node}
        _keep = [o for o in _m.opset_import if o.domain in _used or o.domain == ""]
        del _m.opset_import[:]
        _m.opset_import.extend(_keep)
        _so = ort.SessionOptions()
        _so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
        sess = ort.InferenceSession(_m.SerializeToString(), _so)
        wins = real_windows(model, a.cache, a.golden_n, seed=7, lookahead=L)
        fq = {n: v.astype(np.float32).reshape(1, CH, 1, 1) for n, v in film}
        xs, ys = [], []
        for w, _fp, _y in wins:
            xs.append(np.clip(np.round(w / si) + zi, -128, 127).astype(np.int8))
            yf = sess.run(None, {"rsn_in": w.astype(np.float32), **fq})[0].reshape(-1)
            ys.append(np.clip(np.round(yf / so) + zo, -128, 127).astype(np.int8))
        np.savez(out / "golden.npz", input_q8=np.stack(xs), output_q8=np.stack(ys),
                 **{f"{n}_q8": np.clip(np.round(v / q[n][0]) + q[n][1], -128, 127).astype(np.int8)
                    for n, v in film})
        g = ["/* rsn_golden.h - generated by rsn.package, do not edit\n"
             " * Real input windows and the host INT8 graph's outputs for them, with\n"
             " * rsn_film.h's FiLM inputs. The NPU rounds a little differently. */\n",
             "#pragma once\n#include <stdint.h>\n\n",
             f"#define RSN_GOLDEN_N {len(xs)}\n#define RSN_GOLDEN_LEN {WINDOW}\n\n"]
        for k, (xq, yq) in enumerate(zip(xs, ys)):
            g.append(_c_array(f"rsn_golden_in{k}", xq.reshape(-1), "int8_t", "{:d}"))
            g.append(_c_array(f"rsn_golden_out{k}", yq.reshape(-1), "int8_t", "{:d}"))
        (out / "rsn_golden.h").write_text("".join(g))
        print(f"   golden vectors: {len(xs)} real windows -> golden.npz, rsn_golden.h")

    (out / "README.md").write_text(f"""# Deployed RSN

Built {dep['generated']} from `{a.ckpt}`, step {dep['step']}{', quantization-aware' if dep['qat'] else ''}.

| | |
|---|---|
| architecture | {model.arch()} |
| window / hop | {WINDOW} / {dsp.HOP} samples at 16 kHz |
| lookahead | {L} samples |
| output used | [{o0}, {o1}) of each window |
| residual scale | {res_scale:.6g} (applied to the residual input, divided out of the output) |
| input quantization | scale {si:.6g}, zero point {zi} |
| output quantization | scale {so:.6g}, zero point {zo} |
| singer embedding | {emb_src} |

`rsn_film.h` holds the FiLM inputs for the embedding, and `rsn_golden.h` real
input windows with the host graph's outputs, used by the boot self-test.
""")
    print(f"-> {out}/  (rsn_int8.onnx, rsn_film.h, rsn_deploy.json, README.md)")
    print(f"   L={L}, slice [{o0},{o1}), RES_SCALE {res_scale:.4g}, embedding: {emb_src}")


if __name__ == "__main__":
    main()
